import dotenv from 'dotenv';
dotenv.config();

interface Config {
    AUTH_USER_SERVICE_DATABASE_URL : string
    REDIS_URL : string;
    SERVICE_NAME : string;
    NODEMAILER_EMAIL : string;
    NODEMAILER_PASS : string;
    ACCESS_TOKEN_SECRET : string;
    REFRESH_TOKEN_SECRET : string;
    GRPC_AUTH_USER_SERVICE_SERVER_URL : string;
    JWT_REFRESH_TOKEN_EXPIRY : string;
    JWT_ACCESS_TOKEN_EXPIRY : string;
    NODEMAILER_SERVICE : string;
    OTP_EXPIRY_SECONDS : number;
    AUTH_USER_SERVICE_METRICS_PORT : number;
    PROFILE_CACHE_EXPIRY : number;
    BLOCKED_USER_CACHE_EXPIRY : number;
}

export const config : Config = {
     AUTH_USER_SERVICE_DATABASE_URL : process.env.AUTH_USER_SERVICE_DATABASE_URL!,
     ACCESS_TOKEN_SECRET : process.env.JWT_ACCESS_TOKEN_SECRET!,
     REFRESH_TOKEN_SECRET : process.env.JWT_REFRESH_TOKEN_SECRET!,
     REDIS_URL : process.env.REDIS_URL!,
     SERVICE_NAME : "AUTH_USER_SERVICE",
     NODEMAILER_EMAIL : process.env.NODEMAILER_EMAIL!,
     NODEMAILER_PASS : process.env.NODEMAILER_PASS!,
     GRPC_AUTH_USER_SERVICE_SERVER_URL : process.env.GRPC_AUTH_USER_SERVICE_SERVER_URL!,
     JWT_ACCESS_TOKEN_EXPIRY : process.env.JWT_ACCESS_TOKEN_EXPIRY!,
     JWT_REFRESH_TOKEN_EXPIRY : process.env.JWT_REFRESH_TOKEN_EXPIRY!,
     NODEMAILER_SERVICE : process.env.NODEMAILER_SERVICE!,
     OTP_EXPIRY_SECONDS : Number(process.env.OTP_EXPIRY_SECONDS)!,
     AUTH_USER_SERVICE_METRICS_PORT : Number(process.env.AUTH_USER_SERVICE_METRICS_PORT)!,
     PROFILE_CACHE_EXPIRY : Number(process.env.PROFILE_CACHE_EXPIRY)!,
     BLOCKED_USER_CACHE_EXPIRY : Number(process.env.BLOCKED_USER_CACHE_EXPIRY)!,
}